### ISSUE TITLE
No ui 

### ISSUE THREAD

**Issue by gamer50082** [OfficialRenny/WebYtDL#1]
The whole thing is broken 0-0

**Comment by OfficialRenny** [comment]
Hi, I haven't touched this repo in a long time but it looks like you may need to compile `public/styles/style.less` into `public/styles/dist/style.css` (using a globally installed https://www.npmjs.com/package/less)

The page will also look for a script+stylesheet combo that is used to give the dropdown its appearance (like in the readme screenshots) but those are not included in the repo as I don't have permission to share them.

Other than the styling, the tool should be fully functional though it may require an update of ytdl-core; otherwise, your youtube downloads may be slow.
